name: Publish to crates.io

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo check
      - name: Publish to crates.io
        run: cargo publish --allow-dirty
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  windows-msi:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install WiX Toolset
        run: |
          dotnet tool install --global wix
          cargo install cargo-wix
      - name: Build MSI
        run: cargo wix --output target/release/bootit-$(cargo pkgid | sed 's/.*#//').msi
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/*.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux-release:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - uses: actions/checkout@v4

        - name: Install Rust
          uses: dtolnay/rust-toolchain@stable
          with:
            targets: x86_64-unknown-linux-musl

        - name: Install Cross
          run: cargo install cross --git https://github.com/cross-rs/cross.git

        - name: Build Binary
          run: cross build --release --target x86_64-unknown-linux-musl

        - name: Package Binary
          run: |
            cd target/x86_64-unknown-linux-musl/release
            tar -czf ../../../bootit-linux-x86_64.tar.gz bootit it
            cd ../../../

        - name: Create Release
          uses: softprops/action-gh-release@v2
          with:
            files: bootit-linux-x86_64.tar.gz
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
